// GENERATED by voyant admin generate --routes — do not edit.
// Code-assembled admin route tree for package-delivered pages (packaged-admin
// RFC §4.8 endgame): every extension route contribution becomes a code-based
// route grafted under the workspace layout — NO per-route files exist for
// package-delivered pages. Path literals + typed search contracts stay in
// this module (they are what gives the host typed links via the
// `AdminExtensionRoutesBy*` interfaces merged in `router.tsx`); pages,
// loaders, SSR modes, and boundaries come from the extension contributions
// (resolved from the host-owned registry in `src/lib/admin-extensions.tsx`,
// so app-supplied factory options apply to the assembled routes).
// To eject a route, remove it here (and from the maps below) and add a
// hand-written route file — the generator skips files without this header.
import { createRoute } from "@tanstack/react-router"
import { adminExtensionChildRoutes, adminExtensionRouteOptions } from "@voyant-travel/admin-app"
import {
  bookingDetailSearchSchema,
  bookingJourneySearchSchema,
  bookingNewSearchSchema,
  bookingsIndexSearchSchema,
} from "@voyant-travel/bookings-react/admin"

import { adminExtensions } from "@/lib/admin-extensions"
import { getApiUrl } from "@/lib/env"
import { operatorFetcher } from "@/lib/voyant-fetcher"
import { Route as WorkspaceRoute } from "@/routes/_workspace/route"

// operatorFetcher so SSR loaders forward the request cookie; resolved per
// loader call because `getApiUrl()` reads the runtime origin.
const runtime = () => ({ baseUrl: getApiUrl(), fetcher: operatorFetcher })

const workspace = () => WorkspaceRoute

function extension(id: string) {
  const match = adminExtensions.find((candidate) => candidate.id === id)
  if (!match) {
    throw new Error(`[admin.routes.generated] No registered admin extension "${id}".`)
  }
  return match
}

// ---------------------------------------------------------------------------
// action-ledger
// ---------------------------------------------------------------------------

const actionLedgerExtension = extension("action-ledger")

export const ActionLedgerIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/action-ledger",
  ...adminExtensionRouteOptions(actionLedgerExtension, "action-ledger-index", runtime),
})

// ---------------------------------------------------------------------------
// bookings
// ---------------------------------------------------------------------------

const bookingsExtension = extension("bookings")

export const BookingsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/bookings",
  validateSearch: bookingsIndexSearchSchema,
  ...adminExtensionRouteOptions(bookingsExtension, "bookings-index", runtime),
})

export const BookingsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/bookings/$id",
  validateSearch: bookingDetailSearchSchema,
  ...adminExtensionRouteOptions(bookingsExtension, "bookings-detail", runtime),
})

export const BookingsNewRoute = createRoute({
  getParentRoute: workspace,
  path: "/bookings/new",
  validateSearch: bookingNewSearchSchema,
  ...adminExtensionRouteOptions(bookingsExtension, "bookings-new", runtime),
})

export const BookingsJourneyRoute = createRoute({
  getParentRoute: workspace,
  path: "/catalog/journey/$entityModule/$entityId",
  validateSearch: bookingJourneySearchSchema,
  ...adminExtensionRouteOptions(bookingsExtension, "bookings-journey", runtime),
})

// ---------------------------------------------------------------------------
// commerce
// ---------------------------------------------------------------------------

const commerceExtension = extension("commerce")

export const PromotionsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/promotions",
  ...adminExtensionRouteOptions(commerceExtension, "promotions-index", runtime),
})

// ---------------------------------------------------------------------------
// core
// ---------------------------------------------------------------------------

const coreExtension = extension("core")

export const CoreDashboardRoute = createRoute({
  getParentRoute: workspace,
  path: "/",
  ...adminExtensionRouteOptions(coreExtension, "core-dashboard", runtime),
})

export const CoreAccountRoute = createRoute({
  getParentRoute: workspace,
  path: "/account",
  ...adminExtensionRouteOptions(coreExtension, "core-account", runtime),
})

export const CoreSettingsRoute = createRoute({
  getParentRoute: workspace,
  path: "/settings",
  ...adminExtensionRouteOptions(coreExtension, "core-settings", runtime),
})

const coreSettings = () => CoreSettingsRoute

export const CoreSettingsIndexRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-index", runtime),
})

export const CoreSettingsTeamRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/team",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-team", runtime),
})

export const CoreSettingsApiTokensRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/api-tokens",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-api-tokens", runtime),
})

export const CoreSettingsChannelsRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/channels",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-channels", runtime),
})

export const CoreSettingsTaxesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/taxes",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-taxes", runtime),
})

export const CoreSettingsCostCategoriesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/cost-categories",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-cost-categories", runtime),
})

export const CoreSettingsPricingCategoriesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/pricing-categories",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-pricing-categories", runtime),
})

export const CoreSettingsPriceCatalogsRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/price-catalogs",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-price-catalogs", runtime),
})

export const CoreSettingsProductTypesRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/product-types",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-product-types", runtime),
})

export const CoreSettingsProductTagsRoute = createRoute({
  getParentRoute: coreSettings,
  path: "/product-tags",
  ...adminExtensionRouteOptions(coreExtension, "core-settings-product-tags", runtime),
})

// Settings subtree: the static children above keep literal paths for typed
// links; app-supplied extra settings pages (factory `settings.extraPages`,
// invisible to the generator) bind at runtime via adminExtensionChildRoutes.
export const CoreSettingsRouteWithChildren = CoreSettingsRoute.addChildren([
  CoreSettingsIndexRoute,
  CoreSettingsTeamRoute,
  CoreSettingsApiTokensRoute,
  CoreSettingsChannelsRoute,
  CoreSettingsTaxesRoute,
  CoreSettingsCostCategoriesRoute,
  CoreSettingsPricingCategoriesRoute,
  CoreSettingsPriceCatalogsRoute,
  CoreSettingsProductTypesRoute,
  CoreSettingsProductTagsRoute,
  ...adminExtensionChildRoutes(coreExtension, "core-settings", coreSettings, runtime, {
    exclude: [
      "/",
      "/team",
      "/api-tokens",
      "/channels",
      "/taxes",
      "/cost-categories",
      "/pricing-categories",
      "/price-catalogs",
      "/product-types",
      "/product-tags",
    ],
  }),
])

// ---------------------------------------------------------------------------
// distribution
// ---------------------------------------------------------------------------

const distributionExtension = extension("distribution")

export const DistributionChannelSyncRoute = createRoute({
  getParentRoute: workspace,
  path: "/channel-sync",
  ...adminExtensionRouteOptions(distributionExtension, "distribution-channel-sync", runtime),
})

export const SuppliersIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/suppliers",
  ...adminExtensionRouteOptions(distributionExtension, "suppliers-index", runtime),
})

export const SuppliersDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/suppliers/$id",
  ...adminExtensionRouteOptions(distributionExtension, "suppliers-detail", runtime),
})

// ---------------------------------------------------------------------------
// finance
// ---------------------------------------------------------------------------

const financeExtension = extension("finance")

export const FinanceIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance",
  ...adminExtensionRouteOptions(financeExtension, "finance-index", runtime),
})

export const FinanceInvoicesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/invoices",
  ...adminExtensionRouteOptions(financeExtension, "finance-invoices-index", runtime),
})

export const FinanceInvoicesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/invoices/$id",
  ...adminExtensionRouteOptions(financeExtension, "finance-invoices-detail", runtime),
})

export const FinanceInvoiceNumberSeriesRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/invoice-number-series",
  ...adminExtensionRouteOptions(financeExtension, "finance-invoice-number-series", runtime),
})

export const FinancePaymentsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/payments",
  ...adminExtensionRouteOptions(financeExtension, "finance-payments-index", runtime),
})

export const FinancePaymentsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/payments/$id",
  ...adminExtensionRouteOptions(financeExtension, "finance-payments-detail", runtime),
})

export const FinanceSupplierInvoicesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/supplier-invoices",
  ...adminExtensionRouteOptions(financeExtension, "finance-supplier-invoices-index", runtime),
})

export const FinanceSupplierInvoicesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/supplier-invoices/$id",
  ...adminExtensionRouteOptions(financeExtension, "finance-supplier-invoices-detail", runtime),
})

export const FinanceProfitabilityRoute = createRoute({
  getParentRoute: workspace,
  path: "/finance/profitability",
  ...adminExtensionRouteOptions(financeExtension, "finance-profitability", runtime),
})

// ---------------------------------------------------------------------------
// legal
// ---------------------------------------------------------------------------

const legalExtension = extension("legal")

export const LegalIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal",
  ...adminExtensionRouteOptions(legalExtension, "legal-index", runtime),
})

export const LegalContractsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/contracts",
  ...adminExtensionRouteOptions(legalExtension, "legal-contracts-index", runtime),
})

export const LegalContractsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/contracts/$id",
  ...adminExtensionRouteOptions(legalExtension, "legal-contracts-detail", runtime),
})

export const LegalTemplatesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/templates",
  ...adminExtensionRouteOptions(legalExtension, "legal-templates-index", runtime),
})

export const LegalTemplatesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/templates/$id",
  ...adminExtensionRouteOptions(legalExtension, "legal-templates-detail", runtime),
})

export const LegalPoliciesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/policies",
  ...adminExtensionRouteOptions(legalExtension, "legal-policies-index", runtime),
})

export const LegalPoliciesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/policies/$id",
  ...adminExtensionRouteOptions(legalExtension, "legal-policies-detail", runtime),
})

export const LegalNumberSeriesRoute = createRoute({
  getParentRoute: workspace,
  path: "/legal/number-series",
  ...adminExtensionRouteOptions(legalExtension, "legal-number-series", runtime),
})

// ---------------------------------------------------------------------------
// notifications
// ---------------------------------------------------------------------------

const notificationsExtension = extension("notifications")

export const NotificationsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-index", runtime),
})

export const NotificationsTemplatesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/templates",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-templates-index", runtime),
})

export const NotificationsTemplatesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/templates/$id",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-templates-detail", runtime),
})

export const NotificationsReminderRulesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/reminder-rules",
  ...adminExtensionRouteOptions(
    notificationsExtension,
    "notifications-reminder-rules-index",
    runtime,
  ),
})

export const NotificationsReminderRulesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/reminder-rules/$id",
  ...adminExtensionRouteOptions(
    notificationsExtension,
    "notifications-reminder-rules-detail",
    runtime,
  ),
})

export const NotificationsDeliveriesRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/deliveries",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-deliveries", runtime),
})

export const NotificationsReminderRunsRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/reminder-runs",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-reminder-runs", runtime),
})

export const NotificationsPreviewRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/preview",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-preview", runtime),
})

export const NotificationsSettingsRoute = createRoute({
  getParentRoute: workspace,
  path: "/notifications/settings",
  ...adminExtensionRouteOptions(notificationsExtension, "notifications-settings", runtime),
})

// ---------------------------------------------------------------------------
// operations
// ---------------------------------------------------------------------------

const operationsExtension = extension("operations")

export const AvailabilityIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/availability",
  ...adminExtensionRouteOptions(operationsExtension, "availability-index", runtime),
})

export const AvailabilitySlotDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/availability/$id",
  ...adminExtensionRouteOptions(operationsExtension, "availability-slot-detail", runtime),
})

export const AvailabilityRuleDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/availability/rules/$id",
  ...adminExtensionRouteOptions(operationsExtension, "availability-rule-detail", runtime),
})

export const AvailabilityStartTimeDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/availability/start-times/$id",
  ...adminExtensionRouteOptions(operationsExtension, "availability-start-time-detail", runtime),
})

export const ResourcesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/resources",
  ...adminExtensionRouteOptions(operationsExtension, "resources-index", runtime),
})

export const ResourcesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/resources/$id",
  ...adminExtensionRouteOptions(operationsExtension, "resources-detail", runtime),
})

export const ResourcesPoolDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/resources/pools/$id",
  ...adminExtensionRouteOptions(operationsExtension, "resources-pool-detail", runtime),
})

export const ResourcesAssignmentDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/resources/assignments/$id",
  ...adminExtensionRouteOptions(operationsExtension, "resources-assignment-detail", runtime),
})

export const ResourcesAllocationDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/operations/resources/allocations/$id",
  ...adminExtensionRouteOptions(operationsExtension, "resources-allocation-detail", runtime),
})

// ---------------------------------------------------------------------------
// quotes
// ---------------------------------------------------------------------------

const quotesExtension = extension("quotes")

export const QuotesIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/quotes",
  ...adminExtensionRouteOptions(quotesExtension, "quotes-index", runtime),
})

export const QuotesDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/quotes/$id",
  ...adminExtensionRouteOptions(quotesExtension, "quotes-detail", runtime),
})

// ---------------------------------------------------------------------------
// relationships
// ---------------------------------------------------------------------------

const relationshipsExtension = extension("relationships")

export const RelationshipsPeopleIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/people",
  ...adminExtensionRouteOptions(relationshipsExtension, "relationships-people-index", runtime),
})

export const RelationshipsPeopleDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/people/$id",
  ...adminExtensionRouteOptions(relationshipsExtension, "relationships-people-detail", runtime),
})

export const RelationshipsOrganizationsIndexRoute = createRoute({
  getParentRoute: workspace,
  path: "/organizations",
  ...adminExtensionRouteOptions(
    relationshipsExtension,
    "relationships-organizations-index",
    runtime,
  ),
})

export const RelationshipsOrganizationsDetailRoute = createRoute({
  getParentRoute: workspace,
  path: "/organizations/$id",
  ...adminExtensionRouteOptions(
    relationshipsExtension,
    "relationships-organizations-detail",
    runtime,
  ),
})

// ---------------------------------------------------------------------------
// tree + typed-link maps
// ---------------------------------------------------------------------------

export const adminExtensionRoutes = [
  ActionLedgerIndexRoute,
  BookingsIndexRoute,
  BookingsDetailRoute,
  BookingsNewRoute,
  BookingsJourneyRoute,
  PromotionsIndexRoute,
  CoreDashboardRoute,
  CoreAccountRoute,
  CoreSettingsRouteWithChildren,
  DistributionChannelSyncRoute,
  SuppliersIndexRoute,
  SuppliersDetailRoute,
  FinanceIndexRoute,
  FinanceInvoicesIndexRoute,
  FinanceInvoicesDetailRoute,
  FinanceInvoiceNumberSeriesRoute,
  FinancePaymentsIndexRoute,
  FinancePaymentsDetailRoute,
  FinanceSupplierInvoicesIndexRoute,
  FinanceSupplierInvoicesDetailRoute,
  FinanceProfitabilityRoute,
  LegalIndexRoute,
  LegalContractsIndexRoute,
  LegalContractsDetailRoute,
  LegalTemplatesIndexRoute,
  LegalTemplatesDetailRoute,
  LegalPoliciesIndexRoute,
  LegalPoliciesDetailRoute,
  LegalNumberSeriesRoute,
  NotificationsIndexRoute,
  NotificationsTemplatesIndexRoute,
  NotificationsTemplatesDetailRoute,
  NotificationsReminderRulesIndexRoute,
  NotificationsReminderRulesDetailRoute,
  NotificationsDeliveriesRoute,
  NotificationsReminderRunsRoute,
  NotificationsPreviewRoute,
  NotificationsSettingsRoute,
  AvailabilityIndexRoute,
  AvailabilitySlotDetailRoute,
  AvailabilityRuleDetailRoute,
  AvailabilityStartTimeDetailRoute,
  ResourcesIndexRoute,
  ResourcesDetailRoute,
  ResourcesPoolDetailRoute,
  ResourcesAssignmentDetailRoute,
  ResourcesAllocationDetailRoute,
  QuotesIndexRoute,
  QuotesDetailRoute,
  RelationshipsPeopleIndexRoute,
  RelationshipsPeopleDetailRoute,
  RelationshipsOrganizationsIndexRoute,
  RelationshipsOrganizationsDetailRoute,
]

export interface AdminExtensionRoutesByFullPath {
  "/action-ledger": typeof ActionLedgerIndexRoute
  "/bookings": typeof BookingsIndexRoute
  "/bookings/$id": typeof BookingsDetailRoute
  "/bookings/new": typeof BookingsNewRoute
  "/catalog/journey/$entityModule/$entityId": typeof BookingsJourneyRoute
  "/promotions": typeof PromotionsIndexRoute
  "/": typeof CoreDashboardRoute
  "/account": typeof CoreAccountRoute
  "/settings": typeof CoreSettingsRouteWithChildren
  "/settings/": typeof CoreSettingsIndexRoute
  "/settings/team": typeof CoreSettingsTeamRoute
  "/settings/api-tokens": typeof CoreSettingsApiTokensRoute
  "/settings/channels": typeof CoreSettingsChannelsRoute
  "/settings/taxes": typeof CoreSettingsTaxesRoute
  "/settings/cost-categories": typeof CoreSettingsCostCategoriesRoute
  "/settings/pricing-categories": typeof CoreSettingsPricingCategoriesRoute
  "/settings/price-catalogs": typeof CoreSettingsPriceCatalogsRoute
  "/settings/product-types": typeof CoreSettingsProductTypesRoute
  "/settings/product-tags": typeof CoreSettingsProductTagsRoute
  "/channel-sync": typeof DistributionChannelSyncRoute
  "/suppliers": typeof SuppliersIndexRoute
  "/suppliers/$id": typeof SuppliersDetailRoute
  "/finance": typeof FinanceIndexRoute
  "/finance/invoices": typeof FinanceInvoicesIndexRoute
  "/finance/invoices/$id": typeof FinanceInvoicesDetailRoute
  "/finance/invoice-number-series": typeof FinanceInvoiceNumberSeriesRoute
  "/finance/payments": typeof FinancePaymentsIndexRoute
  "/finance/payments/$id": typeof FinancePaymentsDetailRoute
  "/finance/supplier-invoices": typeof FinanceSupplierInvoicesIndexRoute
  "/finance/supplier-invoices/$id": typeof FinanceSupplierInvoicesDetailRoute
  "/finance/profitability": typeof FinanceProfitabilityRoute
  "/legal": typeof LegalIndexRoute
  "/legal/contracts": typeof LegalContractsIndexRoute
  "/legal/contracts/$id": typeof LegalContractsDetailRoute
  "/legal/templates": typeof LegalTemplatesIndexRoute
  "/legal/templates/$id": typeof LegalTemplatesDetailRoute
  "/legal/policies": typeof LegalPoliciesIndexRoute
  "/legal/policies/$id": typeof LegalPoliciesDetailRoute
  "/legal/number-series": typeof LegalNumberSeriesRoute
  "/notifications": typeof NotificationsIndexRoute
  "/notifications/templates": typeof NotificationsTemplatesIndexRoute
  "/notifications/templates/$id": typeof NotificationsTemplatesDetailRoute
  "/notifications/reminder-rules": typeof NotificationsReminderRulesIndexRoute
  "/notifications/reminder-rules/$id": typeof NotificationsReminderRulesDetailRoute
  "/notifications/deliveries": typeof NotificationsDeliveriesRoute
  "/notifications/reminder-runs": typeof NotificationsReminderRunsRoute
  "/notifications/preview": typeof NotificationsPreviewRoute
  "/notifications/settings": typeof NotificationsSettingsRoute
  "/operations/availability": typeof AvailabilityIndexRoute
  "/operations/availability/$id": typeof AvailabilitySlotDetailRoute
  "/operations/availability/rules/$id": typeof AvailabilityRuleDetailRoute
  "/operations/availability/start-times/$id": typeof AvailabilityStartTimeDetailRoute
  "/operations/resources": typeof ResourcesIndexRoute
  "/operations/resources/$id": typeof ResourcesDetailRoute
  "/operations/resources/pools/$id": typeof ResourcesPoolDetailRoute
  "/operations/resources/assignments/$id": typeof ResourcesAssignmentDetailRoute
  "/operations/resources/allocations/$id": typeof ResourcesAllocationDetailRoute
  "/quotes": typeof QuotesIndexRoute
  "/quotes/$id": typeof QuotesDetailRoute
  "/people": typeof RelationshipsPeopleIndexRoute
  "/people/$id": typeof RelationshipsPeopleDetailRoute
  "/organizations": typeof RelationshipsOrganizationsIndexRoute
  "/organizations/$id": typeof RelationshipsOrganizationsDetailRoute
}

export interface AdminExtensionRoutesByTo {
  "/action-ledger": typeof ActionLedgerIndexRoute
  "/bookings": typeof BookingsIndexRoute
  "/bookings/$id": typeof BookingsDetailRoute
  "/bookings/new": typeof BookingsNewRoute
  "/catalog/journey/$entityModule/$entityId": typeof BookingsJourneyRoute
  "/promotions": typeof PromotionsIndexRoute
  "/": typeof CoreDashboardRoute
  "/account": typeof CoreAccountRoute
  "/settings": typeof CoreSettingsIndexRoute
  "/settings/team": typeof CoreSettingsTeamRoute
  "/settings/api-tokens": typeof CoreSettingsApiTokensRoute
  "/settings/channels": typeof CoreSettingsChannelsRoute
  "/settings/taxes": typeof CoreSettingsTaxesRoute
  "/settings/cost-categories": typeof CoreSettingsCostCategoriesRoute
  "/settings/pricing-categories": typeof CoreSettingsPricingCategoriesRoute
  "/settings/price-catalogs": typeof CoreSettingsPriceCatalogsRoute
  "/settings/product-types": typeof CoreSettingsProductTypesRoute
  "/settings/product-tags": typeof CoreSettingsProductTagsRoute
  "/channel-sync": typeof DistributionChannelSyncRoute
  "/suppliers": typeof SuppliersIndexRoute
  "/suppliers/$id": typeof SuppliersDetailRoute
  "/finance": typeof FinanceIndexRoute
  "/finance/invoices": typeof FinanceInvoicesIndexRoute
  "/finance/invoices/$id": typeof FinanceInvoicesDetailRoute
  "/finance/invoice-number-series": typeof FinanceInvoiceNumberSeriesRoute
  "/finance/payments": typeof FinancePaymentsIndexRoute
  "/finance/payments/$id": typeof FinancePaymentsDetailRoute
  "/finance/supplier-invoices": typeof FinanceSupplierInvoicesIndexRoute
  "/finance/supplier-invoices/$id": typeof FinanceSupplierInvoicesDetailRoute
  "/finance/profitability": typeof FinanceProfitabilityRoute
  "/legal": typeof LegalIndexRoute
  "/legal/contracts": typeof LegalContractsIndexRoute
  "/legal/contracts/$id": typeof LegalContractsDetailRoute
  "/legal/templates": typeof LegalTemplatesIndexRoute
  "/legal/templates/$id": typeof LegalTemplatesDetailRoute
  "/legal/policies": typeof LegalPoliciesIndexRoute
  "/legal/policies/$id": typeof LegalPoliciesDetailRoute
  "/legal/number-series": typeof LegalNumberSeriesRoute
  "/notifications": typeof NotificationsIndexRoute
  "/notifications/templates": typeof NotificationsTemplatesIndexRoute
  "/notifications/templates/$id": typeof NotificationsTemplatesDetailRoute
  "/notifications/reminder-rules": typeof NotificationsReminderRulesIndexRoute
  "/notifications/reminder-rules/$id": typeof NotificationsReminderRulesDetailRoute
  "/notifications/deliveries": typeof NotificationsDeliveriesRoute
  "/notifications/reminder-runs": typeof NotificationsReminderRunsRoute
  "/notifications/preview": typeof NotificationsPreviewRoute
  "/notifications/settings": typeof NotificationsSettingsRoute
  "/operations/availability": typeof AvailabilityIndexRoute
  "/operations/availability/$id": typeof AvailabilitySlotDetailRoute
  "/operations/availability/rules/$id": typeof AvailabilityRuleDetailRoute
  "/operations/availability/start-times/$id": typeof AvailabilityStartTimeDetailRoute
  "/operations/resources": typeof ResourcesIndexRoute
  "/operations/resources/$id": typeof ResourcesDetailRoute
  "/operations/resources/pools/$id": typeof ResourcesPoolDetailRoute
  "/operations/resources/assignments/$id": typeof ResourcesAssignmentDetailRoute
  "/operations/resources/allocations/$id": typeof ResourcesAllocationDetailRoute
  "/quotes": typeof QuotesIndexRoute
  "/quotes/$id": typeof QuotesDetailRoute
  "/people": typeof RelationshipsPeopleIndexRoute
  "/people/$id": typeof RelationshipsPeopleDetailRoute
  "/organizations": typeof RelationshipsOrganizationsIndexRoute
  "/organizations/$id": typeof RelationshipsOrganizationsDetailRoute
}

export interface AdminExtensionRoutesById {
  "/_workspace/action-ledger": typeof ActionLedgerIndexRoute
  "/_workspace/bookings": typeof BookingsIndexRoute
  "/_workspace/bookings/$id": typeof BookingsDetailRoute
  "/_workspace/bookings/new": typeof BookingsNewRoute
  "/_workspace/catalog/journey/$entityModule/$entityId": typeof BookingsJourneyRoute
  "/_workspace/promotions": typeof PromotionsIndexRoute
  "/_workspace/": typeof CoreDashboardRoute
  "/_workspace/account": typeof CoreAccountRoute
  "/_workspace/settings": typeof CoreSettingsRouteWithChildren
  "/_workspace/settings/": typeof CoreSettingsIndexRoute
  "/_workspace/settings/team": typeof CoreSettingsTeamRoute
  "/_workspace/settings/api-tokens": typeof CoreSettingsApiTokensRoute
  "/_workspace/settings/channels": typeof CoreSettingsChannelsRoute
  "/_workspace/settings/taxes": typeof CoreSettingsTaxesRoute
  "/_workspace/settings/cost-categories": typeof CoreSettingsCostCategoriesRoute
  "/_workspace/settings/pricing-categories": typeof CoreSettingsPricingCategoriesRoute
  "/_workspace/settings/price-catalogs": typeof CoreSettingsPriceCatalogsRoute
  "/_workspace/settings/product-types": typeof CoreSettingsProductTypesRoute
  "/_workspace/settings/product-tags": typeof CoreSettingsProductTagsRoute
  "/_workspace/channel-sync": typeof DistributionChannelSyncRoute
  "/_workspace/suppliers": typeof SuppliersIndexRoute
  "/_workspace/suppliers/$id": typeof SuppliersDetailRoute
  "/_workspace/finance": typeof FinanceIndexRoute
  "/_workspace/finance/invoices": typeof FinanceInvoicesIndexRoute
  "/_workspace/finance/invoices/$id": typeof FinanceInvoicesDetailRoute
  "/_workspace/finance/invoice-number-series": typeof FinanceInvoiceNumberSeriesRoute
  "/_workspace/finance/payments": typeof FinancePaymentsIndexRoute
  "/_workspace/finance/payments/$id": typeof FinancePaymentsDetailRoute
  "/_workspace/finance/supplier-invoices": typeof FinanceSupplierInvoicesIndexRoute
  "/_workspace/finance/supplier-invoices/$id": typeof FinanceSupplierInvoicesDetailRoute
  "/_workspace/finance/profitability": typeof FinanceProfitabilityRoute
  "/_workspace/legal": typeof LegalIndexRoute
  "/_workspace/legal/contracts": typeof LegalContractsIndexRoute
  "/_workspace/legal/contracts/$id": typeof LegalContractsDetailRoute
  "/_workspace/legal/templates": typeof LegalTemplatesIndexRoute
  "/_workspace/legal/templates/$id": typeof LegalTemplatesDetailRoute
  "/_workspace/legal/policies": typeof LegalPoliciesIndexRoute
  "/_workspace/legal/policies/$id": typeof LegalPoliciesDetailRoute
  "/_workspace/legal/number-series": typeof LegalNumberSeriesRoute
  "/_workspace/notifications": typeof NotificationsIndexRoute
  "/_workspace/notifications/templates": typeof NotificationsTemplatesIndexRoute
  "/_workspace/notifications/templates/$id": typeof NotificationsTemplatesDetailRoute
  "/_workspace/notifications/reminder-rules": typeof NotificationsReminderRulesIndexRoute
  "/_workspace/notifications/reminder-rules/$id": typeof NotificationsReminderRulesDetailRoute
  "/_workspace/notifications/deliveries": typeof NotificationsDeliveriesRoute
  "/_workspace/notifications/reminder-runs": typeof NotificationsReminderRunsRoute
  "/_workspace/notifications/preview": typeof NotificationsPreviewRoute
  "/_workspace/notifications/settings": typeof NotificationsSettingsRoute
  "/_workspace/operations/availability": typeof AvailabilityIndexRoute
  "/_workspace/operations/availability/$id": typeof AvailabilitySlotDetailRoute
  "/_workspace/operations/availability/rules/$id": typeof AvailabilityRuleDetailRoute
  "/_workspace/operations/availability/start-times/$id": typeof AvailabilityStartTimeDetailRoute
  "/_workspace/operations/resources": typeof ResourcesIndexRoute
  "/_workspace/operations/resources/$id": typeof ResourcesDetailRoute
  "/_workspace/operations/resources/pools/$id": typeof ResourcesPoolDetailRoute
  "/_workspace/operations/resources/assignments/$id": typeof ResourcesAssignmentDetailRoute
  "/_workspace/operations/resources/allocations/$id": typeof ResourcesAllocationDetailRoute
  "/_workspace/quotes": typeof QuotesIndexRoute
  "/_workspace/quotes/$id": typeof QuotesDetailRoute
  "/_workspace/people": typeof RelationshipsPeopleIndexRoute
  "/_workspace/people/$id": typeof RelationshipsPeopleDetailRoute
  "/_workspace/organizations": typeof RelationshipsOrganizationsIndexRoute
  "/_workspace/organizations/$id": typeof RelationshipsOrganizationsDetailRoute
}
