// GENERATED by voyant admin generate — do not edit.
// Recreate after changing the modules list in voyant.config.*:
//   voyant admin generate

import { createActionLedgerAdminExtension } from "@voyant-travel/action-ledger-react/admin"
import { createRelationshipsAdminExtension } from "@voyant-travel/relationships-react/admin"
import { createQuotesAdminExtension } from "@voyant-travel/quotes-react/admin"
import { createDistributionAdminExtension } from "@voyant-travel/distribution-react/admin"
import { createCommerceAdminExtension } from "@voyant-travel/commerce-react/admin"
import { createBookingsAdminExtension } from "@voyant-travel/bookings-react/admin"
import { createFinanceAdminExtension } from "@voyant-travel/finance-react/admin"
import { createOperationsAdminExtension } from "@voyant-travel/operations-react/admin"
import { createNotificationsAdminExtension } from "@voyant-travel/notifications-react/admin"
import { createLegalAdminExtension } from "@voyant-travel/legal-react/admin"

/**
 * Admin extension factories keyed by module domain. Factories, not
 * instances — hosts call each with localized labels/icons before
 * registering the result.
 */
export const generatedAdminExtensionFactories = {
  actionLedger: createActionLedgerAdminExtension,
  relationships: createRelationshipsAdminExtension,
  quotes: createQuotesAdminExtension,
  distribution: createDistributionAdminExtension,
  commerce: createCommerceAdminExtension,
  bookings: createBookingsAdminExtension,
  finance: createFinanceAdminExtension,
  operations: createOperationsAdminExtension,
  notifications: createNotificationsAdminExtension,
  legal: createLegalAdminExtension,
} as const
