// AUTO-GENERATED by `voyant db schemas --emit` (or `voyant db generate`).
// Source of truth: voyant.config.ts (modules + additionalSchemas + schemas).
// Do not edit by hand — re-run the command to refresh.
export const schema = [
  "../../node_modules/.pnpm/@voyant-travel+db@0.109.5_@cloudflare+workers-types@4.20260702.1_@types+pg@8.20.0_kysely@0.29.2_pg@8.22.0/node_modules/@voyant-travel/db/dist/schema/index.js",
  "../../node_modules/.pnpm/@voyant-travel+action-ledger@0.105.12_@cloudflare+workers-types@4.20260702.1_@neondatabase+se_2gz5lz45ngrznwh5vfejvrx7ke/node_modules/@voyant-travel/action-ledger/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+relationships@0.122.2_@cloudflare+workers-types@4.20260702.1_@neondatabase+ser_wagra23wv2quoykjyfglvn6dpy/node_modules/@voyant-travel/relationships/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+quotes@0.124.2_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverless_5stteevjqgz3slbbjqluof4p74/node_modules/@voyant-travel/quotes/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+identity@0.141.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverle_jst7fgufu3k2lguwxk75cyumti/node_modules/@voyant-travel/identity/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+bookings@0.141.1_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverle_vp5yzoyo4s2sujs24rkjcimjje/node_modules/@voyant-travel/bookings/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+distribution@0.131.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serv_s3l2nxmhx4igxrzv564gvploey/node_modules/@voyant-travel/distribution/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+inventory@0.7.1_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_fdbdhbpr3ps5f5yqd6ygovuhzi/node_modules/@voyant-travel/inventory/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+commerce@0.23.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_jggom6svxo5serh67uppemc7aq/node_modules/@voyant-travel/commerce/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+catalog@0.139.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_xekh42r2nxh56wgt4zszdsyhqq/node_modules/@voyant-travel/catalog/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+finance@0.141.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_5fmajk3aqmbly6ez6ifv5m76wy/node_modules/@voyant-travel/finance/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+availability@0.1.1_@cloudflare+workers-types@4.20260702.1_@neondatabase+server_bgfsvon537bttgkcpncoj3ndui/node_modules/@voyant-travel/availability/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+operations@0.5.13_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverl_4vuo67ztbz3op3cg3hdy5pgqxa/node_modules/@voyant-travel/operations/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+notifications@0.118.2_@cloudflare+workers-types@4.20260702.1_@neondatabase+ser_ielqijmc2wlua7eumokicgj6ki/node_modules/@voyant-travel/notifications/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+legal@0.141.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverless@_wiz77tk57ki5bgafhdsdp3mse4/node_modules/@voyant-travel/legal/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+storefront@0.143.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+server_a2p6vhzu2fm4i5uyadpxvstinm/node_modules/@voyant-travel/storefront/dist/verification/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+trips@0.132.1_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverless@_kkaeh5jg6ibjdiacxn4spaumje/node_modules/@voyant-travel/trips/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+operator-settings@0.2.25_@cloudflare+workers-types@4.20260702.1_@neondatabase+_l3q4qgiiycvw3g5rcova3mnzba/node_modules/@voyant-travel/operator-settings/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+accommodations@0.109.9_@cloudflare+workers-types@4.20260702.1_@neondatabase+se_ucmgwo4v4rbl2xqqhohqx6yyru/node_modules/@voyant-travel/accommodations/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+catalog-authoring@0.106.28_@cloudflare+workers-types@4.20260702.1_@neondatabas_wdrcfbskpr4fqi6dpvgkbypbjq/node_modules/@voyant-travel/catalog-authoring/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+workflow-runs@0.111.17_@cloudflare+workers-types@4.20260702.1_@neondatabase+se_bjcifkkflqdhfyoix7kpuwa2ia/node_modules/@voyant-travel/workflow-runs/dist/schema.js",
  "./drizzle.links.generated.ts",
] as const
