// AUTO-GENERATED by `voyant db schemas --emit` (or `voyant db generate`).
// Source of truth: voyant.config.ts (modules + additionalSchemas + schemas).
// Do not edit by hand — re-run the command to refresh.
export const schema = [
  "../../node_modules/.pnpm/@voyant-travel+db@0.109.5_@cloudflare+workers-types@4.20260702.1_@types+pg@8.20.0_kysely@0.29.2_pg@8.22.0/node_modules/@voyant-travel/db/dist/schema/index.js",
  "../../node_modules/.pnpm/@voyant-travel+action-ledger@0.105.12_@cloudflare+workers-types@4.20260702.1_@neondatabase+se_2gz5lz45ngrznwh5vfejvrx7ke/node_modules/@voyant-travel/action-ledger/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+relationships@0.122.1_@cloudflare+workers-types@4.20260702.1_@neondatabase+ser_lrrtkbl5rz7vizraazp2c4sycu/node_modules/@voyant-travel/relationships/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+quotes@0.124.1_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverless_nqpx6mwndwrettg4awbmcay4ii/node_modules/@voyant-travel/quotes/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+identity@0.140.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverle_eeqlpq5bt4p62aioxl53w5ibye/node_modules/@voyant-travel/identity/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+bookings@0.140.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverle_opswwg76whsihapvqyew7pkaki/node_modules/@voyant-travel/bookings/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+distribution@0.130.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serv_lr3fi3472fnezdkhhzmasjqkjq/node_modules/@voyant-travel/distribution/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+inventory@0.7.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_ew7aqdz2rsecglgza6rdohfbim/node_modules/@voyant-travel/inventory/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+commerce@0.22.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_6avgari7lxesywidqsioc24q6u/node_modules/@voyant-travel/commerce/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+catalog@0.138.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_6mrbiwjm7szqzgspzohf3dnsla/node_modules/@voyant-travel/catalog/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+finance@0.140.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverles_pmfeyv3gwbrwb465lhac2go6hi/node_modules/@voyant-travel/finance/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+availability@0.1.1_@cloudflare+workers-types@4.20260702.1_@neondatabase+server_bgfsvon537bttgkcpncoj3ndui/node_modules/@voyant-travel/availability/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+operations@0.5.12_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverl_ylvxkmggpirdoaev5gf6n7nagm/node_modules/@voyant-travel/operations/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+notifications@0.118.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+ser_ckaguzoujrrcbeprqwgsjagqwe/node_modules/@voyant-travel/notifications/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+legal@0.140.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverless@_w5swbms7y5z6qn5enppcieq7ym/node_modules/@voyant-travel/legal/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+storefront@0.142.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+server_xetn73bfvf4axqrg5wyaktoeu4/node_modules/@voyant-travel/storefront/dist/verification/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+trips@0.131.0_@cloudflare+workers-types@4.20260702.1_@neondatabase+serverless@_t4y5eysbydnefrksztv3b7p2sy/node_modules/@voyant-travel/trips/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+operator-settings@0.2.24_@cloudflare+workers-types@4.20260702.1_@neondatabase+_jl47wlvegihgofr4t2q3m3wh2u/node_modules/@voyant-travel/operator-settings/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+accommodations@0.109.7_@cloudflare+workers-types@4.20260702.1_@neondatabase+se_tv2jj4ufpdmfzhimrriahr5ypy/node_modules/@voyant-travel/accommodations/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+catalog-authoring@0.106.28_@cloudflare+workers-types@4.20260702.1_@neondatabas_6zm2cn7uogk4e27rz6ltz2cs2m/node_modules/@voyant-travel/catalog-authoring/dist/schema.js",
  "../../node_modules/.pnpm/@voyant-travel+workflow-runs@0.111.16_@cloudflare+workers-types@4.20260702.1_@neondatabase+se_2xkkcih42ev76to67xyp3kmtci/node_modules/@voyant-travel/workflow-runs/dist/schema.js",
  "./drizzle.links.generated.ts",
] as const
