export const CHANNEL_PUSH_BOOKING_LINK_CRON = "*/15 * * * *"
export const CHANNEL_PUSH_AVAILABILITY_CRON = "0 * * * *"
export const CHANNEL_PUSH_CONTENT_CRON = "0 3 * * *"
export const DRAFT_REAPER_CRON = "5 * * * *"
export const PROMOTION_BOUNDARY_SCHEDULER_CRON = "*/5 * * * *"
export const OUTBOX_DRAIN_CRON = "*/2 * * * *"
export const HOUSEKEEPING_GENERATE_CRON = "0 6 * * *"
